### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by keszybz**
This pull request allows pysb to be used under Python 3.4 (and probably 3.3, but I didn't test that). All tests pass, and things seem to generally work the same as under Python 2.7.

The code is made both Python 2 and 3 compatible. This is the modern approach to doing the conversion. A single codebase makes everything easier and faster. Since the pysb codebase is rather clean, there's no need to use helper modules like six.

### CODE REVIEW

**Comment by keszybz** [comment]
This should fix issue #101 :)

**Comment by jmuhlich** [comment]
This is an amazing amount of work, thank you so much. It will take a little time to review, but we will get to it.

**Comment by jmuhlich** [comment]
OK, I finally reviewed this (although I'll admit I didn't check every line in the print_function one... :) and I just have a small issue with the scipy.weave fix. I'll comment directly on that commit and we can resolve it.

As discussed at #101, do please back out the != operator change. Is there an easy mechanical way for a Python3 user to apply that fix locally?

**Comment by keszybz** [comment]
>  I'll comment directly on that commit and we can resolve it.
Did you comment? I don't see the comment, fwiw.

>  Is there an easy mechanical way for a Python3 user to apply that fix locally?
Partially. Changes to code can be done with 2to3 operator fixer. That wouldn't change documentation. But having just the code changes is enough to use it.

**Comment by keszybz** [comment]
I looked into changing the weave import to be in the try_block, but it makes things more complicated... scipy.weave.build_tools.CompileError is not available if the import fails, so a nested try..except block is needed, etc. I tweaked the implementation from 0441755 to be a bit more readable, but I'm leaving it mostly as is.

I'll submit a new pull request with updated code.

**Pull request closed without merging**
