### PR TITLE
Faster SimulationResult loading: use slices

### PR DESCRIPTION
**Pull request by ortega2247**
According to [h5py](https://h5py.readthedocs.io/en/stable/high/dataset.html#reading-writing-data):  Slice specifications are translated directly to HDF5 “hyperslab” selections, and are a fast and efficient way to access data in the file.

PySB currently passes the `trajectories` h5py Dataset object to the `SimulationResult` object. Then, it iterates over the trajectories. This iteration is slow because it uses the Dataset` __iter__` method. If we access the data first (which it already returns a numpy.array) and iterate over these objects, loading the simulations become faster.

Some benchmarks:

```python
from pysb.simulator import SimulationResult, ScipyOdeSimulator
from pysb.examples.tyson_oscillator import model
import numpy as np

tspan = np.linspace(0, 100, 100)
pars = np.array([p.value for p in model.parameters])
all_pars_10000 = np.tile(pars, (10000, 1))
simulation = ScipyOdeSimulator(model, tspan).run(param_values=all_pars_10000, num_processors=4)
simulation.save('tyson_sims.h5')


def load_function():
    sim = SimulationResult.load('tyson_sims.h5')

if __name__ == '__main__':
    from timeit import Timer
    t1 = Timer("load_function()", "from __main__ import load_function")
    print('Loading sim with 10000 pars            : ', t1.timeit(1))
```
**Results on a Mac**

Slicing Datasets:
Loading sim with 10000 pars            :  1.49567398900035

Current PySB approach:
Loading sim with 10000 pars            :  53.9273291490008

### CODE REVIEW

**Comment by ortega2247** [comment]
I just realize that we could slice expressions, observables and tout. This would speedup the loading time when the simulations are saved with observables and expressions

**Comment by ortega2247** [comment]
Also, is there a reason to return the observables and expressions as lists instead of numpy arrays? There is a for loop in lines 1247-1251 of base.py in the simulator folder that slows down the loading time of large simulations with observables and expressions. If we could return a numpy array this for loop could be vectorized and that would also speed up the load function

**Comment by jmuhlich** [comment]
@ortega2247 Do you want to add those improvements in this PR or start a new one?

**Comment by ortega2247** [comment]
I am going to start a new PR, so this one can be merged

**Comment by jmuhlich** [comment]
@ortega2247 could you please rebase this or merge master into it so GitHub shows it as up-to-date and mergeable? Thanks. In the future if you leave the "Allow edits from maintainers" box checked when creating a PR then pysb maintainers who aren't in LoLab-VU can do that for you.

**Comment by ortega2247** [comment]
Sounds good! Thanks

**Pull request merged**
