### PR TITLE
Mark run_tutorial_a executable same as other examples

### PR DESCRIPTION
**Pull request by keszybz**
Just for consistency so rpmlint doesn't complain.

### CODE REVIEW

**Comment by keszybz** [comment]
Thanks.

> How does rpmlint determine that this is supposed to be an exectuable script?
It uses some (probably ugly) heuristics. In this case the file has code at the top level (as opposed to functions or classes), and it detects that.

**Comment by alubbock** [comment]
@jmuhlich Any objection to merging this?

**Comment by alubbock** [comment]
I don't have permission to push a commit to resolve the conflict here, so I can't merge it at present. Since this is quite an old PR, I'll close it, but if you'd still like to merge this change please open a new PR against `master` and I'll be happy to take a look. Thanks for your interest in PySB!

**Comment by jmuhlich** [comment]
I was leaving it open as I had started to rethink this from a slightly higher level. Reopened as issue #413 (where I suggest a different fix).

**Pull request closed without merging**
