### PR TITLE
KaSa interface fixes

### PR DESCRIPTION
**Pull request by bgyori**
This PR introduces some small changes to the Kappa interface in PySB to make static analysis (generating contact maps and influence maps) compatible with the 4th generation Kappa tools. First, the executable for static analysis changes from KaSim to KaSa, and second, the output folders for contact map and influence map have to be specified separately.

### CODE REVIEW

**Comment by jmuhlich** [comment]
Something is wrong on Travis, I'll need to sort that out before this can proceed.

**Comment by bgyori** [comment]
Yes, this commit needs to be merged first: https://github.com/pysb/pysb/pull/254/commits/a85b119f9fec1c2bdebdd1b563f19507514a5bc4

**Comment by bgyori** [comment]
Okay so Travis explicitly checks out an old commit of KaSim which I'll need to change before proceeding.

**Comment by bgyori** [comment]
This latest commit should fix the issues with the new installation requirements. There is one KaSim command line option remaining to be updated before tests will pass.

**Comment by bgyori** [comment]
Closing because this PR is superseded by the more general #265 .

**Pull request closed without merging**
