### PR TITLE
Allow constant expressions for compartment sizes

### PR DESCRIPTION
**Pull request by dweindl**
Previously, only parameters were allowed for compartment sizes.
This change allows specifying compartment sizes using constant expressions.

Closes pysb/pysb#524

### CODE REVIEW

**Comment by jmuhlich** [comment]
This is great, thanks! Would you mind adding a new test to exercise the new code path (and might as well check the old one too since we have no test for this). You would edit `pysb/tests/test_core.py` and add something like this (not actually tested!)

```python
@with_model
def test_compartment():
    Parameter('A', 1.0)
    Parameter('B', 2.0)
    Expression('E', A * B)
    Compartment("C1")
    Compartment("C2", C1, 2, A)
    Compartment("C3", C1, 2, E)
```

**Comment by jmuhlich** [comment]
Oh, also `test_invalid_compartment` should get an additional check to assert that a dynamic expression is not valid:

```python
Monomer('A')
Observable('O', A)
Expression('E', O)
assert_raises(Exception, Compartment, 'c2', size=E)
```

**Comment by dweindl** [comment]
Will do, thanks for the pointers!

**Comment by dweindl** [comment]
Tests added as suggested. Worked without changes. The updated `test_compartment` fails with pysb from master (as intended) and passes here. `test_invalid_compartment` passes on master as well as here.

**Comment by jmuhlich** [comment]
Looks like we have some CI failures due to unrelated Sympy changes. I'll work out how to fix those and re-run CI for this PR.

**Review by jmuhlich — APPROVED** [review]

**Comment by jmuhlich** [comment]
Thanks Daniel!

**Comment by dweindl** [comment]
Thank you!

**Pull request merged**
